services:
  - type: web
    name: things-of-korean-line-bot
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: TIMEZONE
        value: Asia/Taipei
      - key: LINE_KOREAN_CHANNEL_SECRET
        sync: false
      - key: LINE_KOREAN_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_KOREAN_TARGET_IDS
        sync: false
      - key: ADMIN_TOKEN
        sync: false
